### PR TITLE
fix for Django 4.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by zerolab** [comment]
@PetrDlouhy would be nice if you could fix any 4.0 warnings as well
e.g. https://github.com/torchbox/wagtail-storages/blob/master/wagtail_storages/__init__.py#L3

corresponding Wagtail core PR https://github.com/wagtail/wagtail/pull/7721

**Comment by PetrDlouhy** [comment]
@zerolab I have added that fix. I didn't find any other warnings in my console regarding `wagtail_storages`.

**Review by zerolab — APPROVED** [review]
LGTM

**Comment by PetrDlouhy** [comment]
@zerolab Can I do anything to get this released?

**Comment by zerolab** [comment]
Hey @PetrDlouhy, I am not a maintainer for wagtail-storages so can't say.
@tm-kn, nudge nudge?

**Comment by tm-kn** [comment]
Thanks for this. I've opened a new PR with a few more changes - #26.

**Pull request closed without merging**
